Map<String, String> arabic = {
  'get_started': 'ابدء',
  'login_here': 'تسجيل الدخول',
  'welcome_back': 'مرحباً بك مرة أخرى\nلقد افتقدناك!',
  'email': 'البريد الإلكتروني',
  'email_required': 'البريد الإلكتروني مطلوب',
  'email_invalid': 'أدخل بريدًا إلكترونيًا صالحًا',
  'password': 'كلمة المرور',
  'password_required': 'كلمة المرور مطلوبة',
  'password_length': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
  'forgot_password': 'هل نسيت كلمة المرور؟',
  'sign_in': 'تسجيل الدخول',
  'create_account': 'إنشاء حساب جديد',
  'or_continue_with': 'أو تابع باستخدام',
  'google_login': 'تسجيل الدخول عبر جوجل',
  'facebook_login': 'تسجيل الدخول عبر فيسبوك',
  'enter_email_address': 'أدخل البريد الإلكتروني',
  'back_to_sign_in': 'العودة لتسجيل الدخول',
  'send': 'إرسال',
  'or': 'أو',
  'have_account': 'هل لديك حساب؟',
  'sign_up': 'إنشاء حساب',
  'create_account_subtitle':
      'أنشئ حسابًا لتتمكن من استكشاف \n جميع الوظائف المتاحة',
  'confirm_password': 'تأكيد كلمة المرور',
  'confirm_password_required': 'يرجى تأكيد كلمة المرور',
  'passwords_not_match': 'كلمات المرور غير متطابقة',
  'already_have_account': 'هل لديك حساب بالفعل',
  'home': 'الرئيسية',
  'jobs': 'وظائف',
  'book': 'الحجز',
  'menu': 'القائمة',
  'featured_activities': 'الأنشطة المميزة',
  'top_listings': 'أفضل القوائم',
  'view_all': 'عرض الكل',

  'paid': 'مدفوع',
  'free': 'مجاني',

  'view_details': 'عرض التفاصيل',
  'book_now': 'احجز الآن',

  'football': 'كرة القدم',
  'gym': 'صالة الألعاب الرياضية',
  'swimming': 'السباحة',
  'tennis': 'التنس',
  'reward': 'المكافأة',
  'car_services': 'خدمات السيارات',
  'faqs': 'الأسئلة الشائعة',
  'notifications': 'الإشعارات',
  'admin': 'المسؤول',
  'logout': 'تسجيل الخروج',
  'edit_name': 'تعديل الاسم',
  'gold_member_points': 'عضو ذهبي - 1200 نقطة',
  'location': 'الموقع',
  'enter_your_location': 'أدخل موقعك',

  'book_a_session': 'حجز جلسة',
  'personal_information': 'المعلومات الشخصية',
  'first_name': 'الاسم الأول',
  'last_name': 'اسم العائلة',
  'email_address': 'البريد الإلكتروني',
  'booking_details': 'تفاصيل الحجز',
  'select_academy': 'اختر الأكاديمية',
  'category': 'الفئة',
  'date': 'التاريخ',
  'number_of_participants': 'عدد المشاركين',
  'age_group': 'الفئة العمرية',
  'select_an_age_group': 'اختر فئة عمرية',
  'special_request': 'طلب خاص',
  'additional_request': 'طلب إضافي',
  'select_an_academy': 'اختر أكاديمية',
  'select_a_category': 'اختر فئة',
  'agree_terms': 'أوافق على الشروط والأحكام\n',
  'booking_agreement': 'بحجز جلسة، فإنك توافق على\n',
  'terms_of_service': 'شروط الخدمة',
  'and': ' و ',
  'privacy_policy': 'سياسة الخصوصية',
  'cancel': 'إلغاء',
  'submit_booking': 'إرسال الحجز',
  'academy_overview': 'نظرة عامة على الأكاديمية',

  'downtown': 'وسط المدينة',
  'reviews_count': '(2 مراجعات)',
  'description': 'الوصف',
  'age_groups': 'الفئات العمرية',
  'children_6_12': 'الأطفال (6-12 سنة)',
  'teenagers_13_18': 'المراهقون (13-18 سنة)',
  'facilities': 'المرافق',
  'opening_hours': 'ساعات العمل',
  'opening_hours_detail':
      'من الاثنين إلى الجمعة: 7:00 صباحًا - 9:00 مساءً، السبت - الأحد: 8:00 صباحًا - 7:00 مساءً',
  'reviews': 'التقييمات',
  'olympic_pool': 'مسبح أولمبي',
  'changing_rooms': 'غرف تغيير الملابس',
  'shower_facilities': 'مرافق الاستحمام',
  'spectator_area': 'منطقة المشاهدين',

  'phone': 'هاتف',
  'website': 'الموقع الإلكتروني',
  'date_month_year': 'اليوم/الشهر/السنة',
  'time': 'الوقت',
  'number_of_person': 'عدد الأشخاص',
  'contact_information': 'معلومات الاتصال',
  'home_title': "اعثر على أكاديمية رياضية أو حضانة مثالية",
  'home_sub_title':
      "اكتشف أفضل الأكاديميات الرياضية والحضانات في منطقتك. قم بحجز الجلسات بسهولة وتتبع تقدمك.",
  'home_bottom_title': "هل أنت مستعد للبدء؟",
  'home_bottom_sub_title':
      "انضم إلى آلاف الآباء الذين وجدوا الأكاديمية المثالية لأطفالهم.",

  'academies_1_title': "أكاديمية السباحة النخبة",
  'academies_2_title': "مركز القوة للياقة البدنية",
  'academies_3_title': "نادي إيس للتنس",
  'academies_4_title': "مركز هووبس لكرة السلة",
  'academies_5_title': "نادي إيس للتنس",
  'academies_6_title': "روضة البدايات المشرقة",

  'academies_1_details':
      "تقدم أكاديمية السباحة النخبة دروس سباحة محترفة للأطفال والمراهقين. مسبحنا الأولمبي والمدربون المعتمدون يضمنون تدريبًا عالي الجودة.",
  'academies_2_details': "مركز القوة مجهز بأجهزة حديثة ومدربين شخصيين معتمدين.",
  'academies_3_details':
      "انضم إلى نادي إيس للتنس للاستمتاع بالتدريب الممتاز والمرافق لجميع المستويات.",
  'academies_4_details':
      "يقدم مركز هووبس برامج تدريب لجميع الفئات العمرية. يشمل منشآتنا العديد من الملاعب والمعدات المتخصصة.",
  'academies_5_details':
      "يوفر نادي إيس للتنس تدريب تنس عالمي المستوى لجميع الأعمار والمستويات. تشمل مرافقنا ملاعب داخلية وخارجية.",
  'academies_6_details':
      "تركز روضة البدايات المشرقة على تنمية الطفولة المبكرة في بيئة ممتعة وجذابة. نقدم مزيجًا متوازنًا من اللعب والأنشطة المنظمة.",
  'apply_filters': 'تطبيق الفلاتر',

  'all_location': 'كل المواقع',

  'rating': 'التقييم',
  'price': 'السعر',
  'reset': 'إعادة تعيين',
  'how_it_works': 'كيف يعمل',

  'points_earn_history': 'تاريخ كسب النقاط',
  'booking': 'حجز',
  'earned_points_on': 'تم الحصول على 10 نقاط في أبريل',
  'available_rewards': 'المكافآت المتاحة',
  'off_next_booking': 'خصم 10% على الحجز التالي',
  'get_discount_text': 'احصل على خصم 10٪ على الحجز التالي في أي أكاديمية.',
  'redeem': 'استرداد',
  'gold_member': 'عضو ذهبي',
  'points': 'نقاط',

  'earn_points_info': 'اكسب 10 نقاط عن كل حجز تقوم به عبر منصتنا.',
  'faq_q1': 'كيف يمكنني حجز جلسة؟',
  'faq_a1': 'قم بزيارة صفحة الحجز، املأ النموذج، وانقر على "إرسال الحجز".',

  'faq_q2': 'هل يمكنني إلغاء أو إعادة جدولة جلسة؟',
  'faq_a2':
      'نعم، يمكنك الإلغاء أو إعادة الجدولة قبل 24 ساعة على الأقل من الجلسة.',

  'faq_q3': 'ما هي طرق الدفع المقبولة؟',
  'faq_a3':
      'نقبل بطاقات الائتمان، وبطاقات الخصم، والتحويلات الآمنة عبر الإنترنت.',

  'faq_q4': 'هل هناك سياسة استرداد؟',
  'faq_a4': 'يتم تقديم استرداد للطلبات الملغاة قبل 24 ساعة على الأقل.',

  'faq_q5': 'كيف أتواصل مع الدعم؟',
  'faq_a5':
      'يمكنك التواصل مع الدعم عبر صفحة الاتصال أو البريد الإلكتروني support@example.com.',

  'faq_q6': 'هل هناك خصومات للحجوزات الجماعية؟',
  'faq_a6': 'نعم، نقدم خصومات للحجوزات التي تشمل 3 مشاركين أو أكثر.',

  'faq_q7': 'هل يمكنني حضور الجلسات بدون تسجيل؟',
  'faq_a7': 'التسجيل مطلوب لجميع الجلسات لضمان توفر الأماكن.',

  'faq_q8': 'هل توفرون المعدات؟',
  'faq_a8': 'نوفر المعدات الأساسية لمعظم الجلسات، لكن يرجى التحقق عند الحجز.',

  'faq_q9': 'هل الجلسات مناسبة للمبتدئين؟',
  'faq_a9': 'نعم، نقدم جلسات مناسبة للمبتدئين في جميع الفئات.',

  'faq_q10': 'ماذا يحدث إذا ألغت الأكاديمية الجلسة؟',
  'faq_a10': 'ستتم إعلامك فوراً وعرض إعادة جدولة أو استرداد كامل.',
  'Arabic': 'عربى',
  'language': 'اللغة',
  'nurseries': 'مدارس الرياضة',
  'sprots_academies': 'اكاديمية الرياضة',
  'comming_soon': 'قريبا',
  'loyalty_points': 'نقاط الولاءية',
  "activity.swimming.downtown": "السباحة | وسط المدينة",
  "activity.gym.uptown": "النادي الرياضي | الأحياء العليا",
  "activity.tennis.westside": "التنس | الجانب الغربي",
  "activity.basketball.downtown": "كرة السلة | وسط المدينة",
  "activity.tennis.southside": "التنس | الجانب الجنوبي",
  "activity.school.southside": "المدرسة | الجانب الجنوبي",
  'history': 'التاريخ',
  'all_sports': 'جميع الرياضات',
  'booking_date': 'تاريخ الحجز',
  'booking_time': 'وقت الحجز',
  'additional_notes': 'ملاحظات اضافية',
  'review_status: PENDING': 'حالة المراجعة: معلقة',
  'booking_successful': 'الحجز بنجاح',
  'ok': 'موافق',
  'error': 'خطأ',
  'email_pass_wrong': "البريد الإلكتروني وكلمة المرور لا يمكن أن يكونا فارغين",
  "Success": "نجاح",
  "Account created successfully": "تم إنشاء الحساب بنجاح",
  "Sign Up Error": "خطأ في التسجيل",
  "Sign In Error": "خطأ في تسجيل الدخول",
  "login_success": "تم تسجيل الدخول بنجاح",
  "Something went wrong. Please try again later.":
      "حدث خطأ. يرجى المحاولة لاحقاً.",
  "The email address is not valid.": "عنوان البريد الإلكتروني غير صالح.",
  "No account found with this email.":
      "لم يتم العثور على حساب مع هذا البريد الإلكتروني.",
  "The password you entered is incorrect.":
      "كلمة المرور التي أدخلتها غير صحيحة.",
  "Google sign-in was cancelled": "تم إلغاء تسجيل الدخول عبر Google",
  "Missing access token": "مفقود رمز الوصول",
  "Failed to retrieve user": "فشل في استرجاع المستخدم",
  "Logged in with Google": "تم تسجيل الدخول باستخدام Google",
  "Google Sign-In Error": "خطأ في تسجيل الدخول عبر Google",
  "Cancelled": "تم الإلغاء",
  "no_notifications": "لا توجد إشعارات.",
  'no_booking_found': 'لم يتم العثور على حجز',
  'choose_your_language': 'Choose your language',
  'change_your_language': 'تغيير اللغة',
  'please_select_a_date': 'يرجى تحديد تاريخ',
  'please_select_a_time': 'يرجى تحديد وقت',
  'please_select_numeber_of_persons': 'يرجى تحديد عدد الاشخاص',
  'gender': 'النوع',
  'all_main_categories': 'جميع الفئات الرئيسية',
  'all_sub_categories': 'جميع الفئات الفرعية',
  'discount': 'خصم',
  'write_review_title': 'اكتب تقييمًا',
  'share_experience_subtitle': 'شارك تجربتك مع هذه الأكاديمية',
  'rating_header': 'التقييم',
  'your_review_header': 'مراجعتك',
  'review_hint': 'أخبر الآخرين عن تجربتك...',
  'review_empty_error': 'لا يمكن أن يكون التقييم فارغًا',
  'rating_empty_error': 'لا يمكن أن يكون التقييم فارغًا',
  'review_success': 'تم إرسال التقييم',
  'review_success_title': 'نجاح',
  'review_error_title': 'خطأ',
  'review_error_message': 'فشل في إرسال التقييم:',
  'submit_review_button': 'إرسال التقييم',
  'cancel_button': 'إلغاء',
  'review_status_rejected': 'حالة التقييم: مرفوض',
  'ratings_label': 'التقييمات:',
  'write_review': 'اكتب تقييمًا',
  'booking_pending': 'الحجز معلق',
  'booking_unpaid': 'الحجز غير مدفوع',
  'booking_unpaid_pending': 'الحجز غير مدفوع ومعلق',
  'booking_cancelled': 'تم إلغاء الحجز',
};
